name: A workflow for testint github action
on: push

jobs:

  upload:
    name: create a text a try to export it as artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - run: |
          ls -l
          sudo echo "this is an other test bur from github action only" > ./test_file
      - uses: actions/upload-artifact@v2
        with:
          name: artifact_test_file
          path: ./test_file
      - uses: actions/upload-artifact@v2
        with:
          name: artifact_test_contained
          path: /home/runner/work/_temp/_github_home/test_contained


  download:
    name: download
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with: 
          name: artifact_test_file
      - uses: actions/download-artifact@v2
        with: 
          name: artifact_test_contained
      - run: |
          ls -R
          #cat test_contained
          #cat /home/github/ref/test
          #cat /home/github/ref/test_contained
