name: A workflow for testint github action
on: push

jobs:

  upload:
    name: create a text a try to export it as artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - run: |
          sudo touch /temp/test
          sudo echo "this is an other test bur from github action only" > /temp/test
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            /home/runner/work/_temp/_github_home/test
            /temp/test

  download:
    name: download
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /wtf
      - run: |
          cat /wtf/test
          cat /wtf/test_contained
