name: A workflow for testint github action
on: push

jobs:

  upload:
    name: create a text a try to export it as artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository:  ArthurHodot/Github_Actions_Private_Test
          token: ${{ secrets.ACCESS_TOKEN_PIRVATE_REPOS }}
          path: private
      - uses: ./
      - run: |
          ls -l private
          sudo echo "this is an other test bur from github action only" > ./test_file
      - uses: actions/upload-artifact@v2
        with:
          name: artifact_test_file
          path: ./test_file
      - uses: actions/upload-artifact@v2
        with:
          name: artifact_test_contained
          path: /home/runner/work/_temp/_github_home/test_contained
      - uses: actions/upload-artifact@v2
        with:
          name: artifact_private
          path: ./private/private_message

  download:
    name: download
    needs: upload
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v2
        with: 
          name: artifact_test_file
      
      - uses: actions/download-artifact@v2
        with: 
          name: artifact_test_contained
      
      - uses: actions/download-artifact@v2
        with: 
          name: artifact_private
      
      - run: |
          ls -R
          cat test_file
          cat test_contained
          cat private_message
