name: A workflow for testint github action
on: push

jobs:
  build:
    name: create a text a try to export it as artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - run: cat /home/runner/work/_temp/_github_home/test
