name: Workflows for testing tags
on:
  push:
    tags:
      - dev_deploy

jobs:

  tag:
    runs-on: ubuntu-latest
    
    steps:
  
      - uses: actions/checkout@v2

      - name: echo ref
        run: echo ref
